CREATE  DATABASE  db  CHARACTER SET utf8 COLLATE DEFAULT;

CREATE TABLE db.company (
id INT UNSIGNED AUTO_INCREMENT NOT NULL,
title  VARCHAR(100) NOT NULL,
estimated_earnings  INT UNSIGNED NULL,
pid INT UNSIGNED NULL,
total INT UNSIGNED NULL,
PRIMARY KEY(id)
) ENGINE=InnoDB CHARACTER SET=UTF8;
